### ISSUE TITLE
Showing color in dialog with \Z escape sequences

### ISSUE THREAD

**Issue by pmulgaonkar** [frougon/pythondialog#14]
Trying to create a msgbox with color as d.msgbox("\Z1test\Zn regular",color=True) renders the string text in red with the text regular in the usual black color. However, the \ characters preceeding both the Zs remain in the text. So the above text gets rendered as `\ test \ regular`  with the colors correct.

Am I missing something?
![image](https://user-images.githubusercontent.com/5150672/226062320-b4e9aa56-0f91-4203-baff-67040d78aa6e.png)

pythondialog = 3.5.3
dialog = Version: 1.3-20171209

**Comment by frougon** [comment]
Hi,

First, you need `colors=True` rather than `color=True`. Disregarding this detail, the reported problem appears to be one of your dialog version and has nothing to do with pythondialog. This has already been reported in #12. At least, I can't reproduce it with dialog 1.3-20230209.

You could most probably have found this by simply doing your test with dialog. Most of the “bugs“ reported on pythondialog are really bugs in some particular version of dialog, and I am getting a bit tired of it...

```
from dialog import Dialog
d = Dialog(dialog="dialog")
d.msgbox(r"\Z1test\Zn regular", colors=True)
```

![Screenshot_2023-03-18_00-39-12](https://user-images.githubusercontent.com/5341798/226070487-bd919b76-1dbb-4300-8462-e9ec8dbde93e.png)

```
$ dialog --version
Version: 1.3-20230209
```

**Comment by frougon** [comment]
Duplicate of #12
