### ISSUE TITLE
\n and \\n handled the same by msgbox

### ISSUE THREAD

**Issue by ChristianTacke** [frougon/pythondialog#8]
```python
from dialog import Dialog
d = Dialog()
d.msgbox("a\nb")
d.msgbox("c\\nd")
print("a\nb")
print("c\\nd")
```

Both `msgbox`es show two lines.
The `print` shows something different.

Is this on purpose?

Debian, python3-dialog 3.5.1, Python 3.7.3, dialog 1.3-20190211-1

**Comment by frougon** [comment]
Hello,

This is due to a `dialog` feature that can be turned off with `--no-nl-expand`. In order to pass the option when using `pythondialog`, there are basically two ways:

* For a one-off use, see [Passing dialog “common options”](http://pythondialog.sourceforge.net/doc/Dialog_class_overview.html#passing-dialog-common-options), e.g. `d.msgbox("c\\nd", no_nl_expand=True)`.

* On the other hand, if you want the option to be always active for a given `Dialog` instance, use the [Dialog.add_persistent_args()](http://pythondialog.sourceforge.net/doc/Dialog_class_overview.html#dialog.Dialog.add_persistent_args) method. For instance, your example can be modified this way:

```python
from dialog import Dialog
d = Dialog()
d.add_persistent_args(["--no-nl-expand"])
d.msgbox("a\nb")
d.msgbox("c\\nd")
print("a\nb")
print("c\\nd")
```

This displays `c\nd` in the second message box.

**Comment by ChristianTacke** [comment]
Thanks for the the really fast answer and the explanation!

From a dialog point of view, this might make sense (I'd rather say "no", but that's not the discussion here).

But from a Python point of view, I don't think, this behaviour makes much sense. Python has very good string/unicode/bytes handling. So if people have a `\\n` in their string, they likely *mean* it.

I see a few options:
* Could you add the `d.add_persistent_args(["--no-nl-expand"])` to some of the examples? Maybe the `simple_example.py`, so that people have a "pythonic" starting point? I don't see `add_persistent_args()` in demo.py either.
* And/or add the `no_nl_expand` arg also somewhere in the examples?
* A backward incompatible change would be to make this the default.

**Comment by frougon** [comment]
Right, I don't want to make this the default because of backward (in)compatibility, and also because I think it's useful to know that when one reads the `dialog(1)` manual page, most things are readily applicable to  `pythondialog` without “expert” knowledge about it. But I agree that showing this in `simple_example.py` and/or `demo.py` would be a good idea.

I'm short on time, will probably do a bit later.

**Comment by ChristianTacke** [comment]
I am coming from the opposite side: I want nice dialogs for Python. So I rarely look at the manpage of dialog, but look at demo.py. And then this `\\n`-business came quite as a surprise. (I first thought, I was doing something wrong.)

> I'm short on time, will probably do a bit later.

Don't panic! :-)
This issue is hopefully visible enough for anyone encountering this problem. And all the info is here.
